import os
import json
import base64
import logging
import urllib.request
import urllib.error

logger = logging.getLogger("jira_client")


def _auth_header() -> str:
    email = os.environ["JIRA_EMAIL"]
    token = os.environ["JIRA_API_TOKEN"]
    return "Basic " + base64.b64encode(f"{email}:{token}".encode()).decode()


def _api_url(path: str) -> str:
    base = os.environ["JIRA_BASE_URL"].rstrip("/")
    return f"{base}/rest/api/3{path}"


def _adf_section_header(text: str) -> dict:
    return {
        "type": "paragraph",
        "content": [{"type": "text", "text": text, "marks": [{"type": "strong"}]}],
    }


def _adf_body(
    description: str | None,
    acceptance_criteria: str | None,
    run_id: int,
    parent_key: str,
    rationale: str | None = None,
    dependency_notes: str | None = None,
    risk_notes: str | None = None,
) -> dict:
    """Build an Atlassian Document Format body for a Jira Cloud Story description."""
    content = []

    if description:
        content.append({
            "type": "paragraph",
            "content": [{"type": "text", "text": description}],
        })

    if acceptance_criteria:
        content.append(_adf_section_header("Acceptance Criteria:"))
        for line in acceptance_criteria.splitlines():
            line = line.strip().lstrip("- ").strip()
            if line:
                content.append({
                    "type": "bulletList",
                    "content": [{
                        "type": "listItem",
                        "content": [{
                            "type": "paragraph",
                            "content": [{"type": "text", "text": line}],
                        }],
                    }],
                })

    if rationale:
        content.append(_adf_section_header("Rationale:"))
        content.append({
            "type": "paragraph",
            "content": [{"type": "text", "text": rationale}],
        })

    if dependency_notes:
        content.append(_adf_section_header("Dependencies:"))
        content.append({
            "type": "paragraph",
            "content": [{"type": "text", "text": dependency_notes}],
        })

    if risk_notes:
        content.append(_adf_section_header("Risks:"))
        content.append({
            "type": "paragraph",
            "content": [{"type": "text", "text": risk_notes}],
        })

    # Traceability footer
    content.append({
        "type": "paragraph",
        "content": [{
            "type": "text",
            "text": f"Generated by AI Dev Orchestrator | Planning run: {run_id} | Parent Epic: {parent_key}",
            "marks": [{"type": "em"}],
        }],
    })

    return {"type": "doc", "version": 1, "content": content}


def create_story_under_epic(
    project_key: str,
    epic_key: str,
    title: str,
    run_id: int,
    description: str | None = None,
    acceptance_criteria: str | None = None,
    rationale: str | None = None,
    dependency_notes: str | None = None,
    risk_notes: str | None = None,
) -> str:
    """Create a Jira Story as a child of the given Epic. Returns the created issue key.

    Requires env vars: JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN.
    Uses Jira Cloud REST API v3 with `parent` field for Epic-Story linking.
    Raises RuntimeError on API errors.
    """
    for var in ("JIRA_BASE_URL", "JIRA_EMAIL", "JIRA_API_TOKEN"):
        if not os.environ.get(var):
            raise RuntimeError(f"Required env var {var} is not set")

    fields: dict = {
        "project":   {"key": project_key},
        "issuetype": {"name": "Story"},
        "summary":   title,
        "parent":    {"key": epic_key},
        "description": _adf_body(
            description, acceptance_criteria, run_id, epic_key,
            rationale=rationale,
            dependency_notes=dependency_notes,
            risk_notes=risk_notes,
        ),
        "labels": ["ai-generated"],
    }

    payload = json.dumps({"fields": fields}).encode()
    req = urllib.request.Request(
        _api_url("/issue"),
        data=payload,
        headers={
            "Authorization": _auth_header(),
            "Content-Type":  "application/json",
            "Accept":        "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            result = json.loads(resp.read())
            return result["key"]
    except urllib.error.HTTPError as exc:
        body = exc.read().decode(errors="replace")
        raise RuntimeError(f"Jira API {exc.code}: {body[:400]}") from exc
